networks:
  my-network:
    ipam:
      config:
        - subnet: 172.25.0.0/16
services:
  mysql_docker:
    image: 'mysql/mysql-server:latest'
    environment:
      '0': MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - '3306:3306'
    volumes:
      - './d-mysql/sql:/var/lib/mysql'
    container_name: mysql_docker
    networks:
      my-network:
        ipv4_address: 172.25.0.5
  redis:
    image: redis
  redissub:
    image: 'matusb42/so1_proyecto_redissub:latest'
    build: ./Redis/sub/
    container_name: redissub
    networks:
      my-network:
        ipv4_address: 172.25.0.3
  redispub:
    image: 'matusb42/so1_proyecto_redispub:latest'
    build: ./Redis/pub/
    ports:
      - '11000:11000'
    container_name: redispub
    networks:
      my-network:
        ipv4_address: 172.25.0.4