#gRPC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-api-deployment
  labels:
    app: front-api
  namespace: so1
spec:
  selector:
    matchLabels:
      app: front-api
  replicas: 1
  template:
    metadata:
      labels:
        app: front-api
    spec:
      containers:
        - name: front-api
          image: 'gcr.io/so1-proyecto-383722/front_api:latest'
          ports:
            - containerPort: 5000
---
#Front API Service with LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: front-api-service
  labels:
    app: front-api
  namespace: so1
spec:
  selector:
    app: front-api
  type: LoadBalancer
  ports:
    - name: front-api
      port: 5000
      targetPort: 5000