#Redis Pub Sub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pub-sub-deployment
spec:
  selector:
    matchLabels:
      app: redis-pub-sub
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pub-sub
    spec:
      containers:
        - name: redis-pub
          image: matusb42/so1_proyecto_redispub:latest
          ports:
            - containerPort: 11000
        - name: redis-sub
          image: matusb42/so1_proyecto_redissub:latest
          
# Redis Pub service will be declared in another .yaml to load-balance with gRPC