#gRPC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  labels:
    app: grpc
  namespace: so1
spec:
  selector:
    matchLabels:
      app: grpc
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc-server
          image: 'gcr.io/so1-proyecto-383722/grpc_server:latest'
          ports:
            - containerPort: 50051
        - name: grpc-client
          image: 'gcr.io/so1-proyecto-383722/grpc_client:latest'
          ports:
            - containerPort: 50061
---
#gRPC Server Service
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
  labels:
    app: grpc
  namespace: so1

spec:
  selector:
    app: grpc
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

---
#gRPC Client Service (For Traffict Split)
apiVersion: v1
kind: Service
metadata:
  name: input-grpc-service
  labels:
    app: input-service
  namespace: so1

spec:
  selector:
    app: grpc
  type: ClusterIP
  ports:
    - name: grpc
      port: 3000  #3000
      targetPort: 50061