#Redis Pub Sub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-v2-0
  namespace: so1
spec:
  selector:
    matchLabels:
      app: target
      version: "2.0"
  replicas: 1
  template:
    metadata:
      labels:
        app: target
        version: "2.0"
    spec:
      containers:
        - name: target-v2-0
          image: 'gcr.io/so1-proyecto-383722/redispub:latest'
          ports:
            - containerPort: 80
        - name: redis-sub
          image: 'gcr.io/so1-proyecto-383722/redissub:latest'
       

---
#Redis Pub Service (For Traffict Split)
apiVersion: v1
kind: Service
metadata:
  name: target-v2-0
  namespace: so1
spec:
  ports:
    - name: redis-pub-sub
      port: 80  #3000
      targetPort: 80
  selector:
    app: target
    version: "2.0"
  # type: ClusterIP


# ---
# #gRPC Client Service (For Traffict Split)
# apiVersion: v1
# kind: Service
# metadata:
#   name: input-redis-service
#   labels:
#     app: input-service
#   namespace: so1

# spec:
#   selector:
#     app: redis-pub-sub
#   type: ClusterIP
#   ports:
#     - name: redis-pub-sub
#       port: 3000  #3000
#       targetPort: 11000


# ---
# #Redis Pub Service (For Traffict Split)
# apiVersion: v1
# kind: Service
# metadata:
#   name: input-redis-service
#   labels:
#     app: input-service
#   namespace: so1

# spec:
#   selector:
#     app: redis-pub-sub
#   type: ClusterIP
#   ports:
#     - name: redis-pub-sub
#       port: 3000 #3000
#       targetPort: 11000