apiVersion: split.smi-spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: target-ts
  namespace: so1
spec:
  service: target-svc
  backends:
  - service: target-v1-0
    weight: 50
  - service: target-v2-0
    weight: 50

